### ISSUE TITLE
Milestone 1: Discovery and specs for OARS V.1

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/openedx-oars#5]
[possibly convert to a label or a milestone field and let epics stand on their own]

- [ ] - [ ] https://github.com/openedx/openedx-oars/issues/7

- [ ] https://github.com/openedx/openedx-oars/issues/8

- [ ] https://github.com/openedx/openedx-oars/issues/9

**Comment by jmakowski1123** [comment]
closing in favor of milestone labels
