### ISSUE TITLE
Technical Discovery for OARS V1

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/openedx-oars#7]
- [ ] https://github.com/openedx/openedx-oars/issues/10
- [ ] https://github.com/openedx/openedx-oars/issues/11
- [ ] De-dupe work on xAPI transforms

**Comment by jmakowski1123** [comment]
closing as a dupe tic
